-- AlterTable
ALTER TABLE "ImageChambre" ADD COLUMN     "creeLe" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ImageHotel" ADD COLUMN     "creeLe" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Visite3DScene" ADD COLUMN     "creeLe" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
